### ISSUE TITLE
用 :deep 书写样式穿透，打包控制台会出现警告

### ISSUE THREAD

**Issue by AlwaysLoveme** [rspack-contrib/rsbuild-plugin-vue2#9]
用官方推荐的 :deep 写穿透样式，打包控制台出现警告：
```
 'deep' is not recognized as a valid pseudo-class. Did you mean '::deep' (pseudo-element) or is this a typo? at static/css/async/9407.8f0e1bca.css:431:28
```

<img width="861" alt="image" src="https://github.com/user-attachments/assets/36c9c0c8-b8a0-4814-93b9-2e3699f275cf">

**Comment by chenjiahan** [comment]
Can you provide a minimal reproduction repository?

**Comment by chenjiahan** [comment]
Get 👌
